# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-10 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_summernote_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='summernote',
            name='hashtag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
