# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-14 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
