# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nou',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='summernote',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Category'),
        ),
    ]
