# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180515_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=300)),
                ('author', models.CharField(default='', max_length=300)),
                ('password', models.CharField(default='', max_length=300)),
                ('parent', models.IntegerField(null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('delete', models.BooleanField(default=0)),
            ],
        ),
    ]
