# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.SummerNote'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='delete',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
