# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180620_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='ip',
            field=models.CharField(default='', max_length=16),
        ),
    ]
