# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_summernote_noc'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip_display',
            field=models.CharField(default='', max_length=16),
        ),
    ]
