# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_ip_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
    ]
