# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='full_delete',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
