# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-21 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_hitlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HitLog',
            new_name='HitCounter',
        ),
    ]
