# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-21 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190121_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HitCounter',
            new_name='HitCount',
        ),
    ]
