# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-21 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190121_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hitcount',
            name='user',
        ),
        migrations.AddField(
            model_name='hitcount',
            name='ip',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 21, 11, 19, 14, 739469, tzinfo=utc), null=True),
        ),
    ]
