# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-21 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190121_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 21, 13, 5, 37, 562902, tzinfo=utc), null=True),
        ),
    ]
