# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-24 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190123_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
