# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-24 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20190124_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitcount',
            name='number_of_get_request',
            field=models.IntegerField(default=0),
        ),
    ]
