# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-24 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_hitcount_number_of_get_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitcount',
            name='ip_display',
            field=models.CharField(default='', max_length=16),
        ),
    ]
