# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-24 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='number_of_get_request',
            field=models.IntegerField(default=0),
        ),
    ]
