# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-24 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statis', '0002_visitor_number_of_get_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='ip_display',
            field=models.CharField(default='', max_length=16),
        ),
    ]
