# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-13 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statis', '0003_visitor_ip_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
